# Install NVIDIA

# exit X11
openbox --exit

# Disable Nouveau
cat >/etc/modprobe.d/nvidia-installer-disable-nouveau.conf <<EOF
# generated by nvidia-installer
blacklist nouveau
options nouveau modeset=0
EOF

update-initramfs -u

reboot

# ------------------------------------------------------------------------------
# Install
# ------------------------------------------------------------------------------

chmod +x NVIDIA-Linux-x86_64-384.90.run

./ NVIDIA-Linux-x86_64-384.90.run

# repair link so we can compile GL stuff
cd /usr/lib
sudo ln -s libGL.so.1 libGL.so 