#!/bin/bash

# 2017-02-06T09:52:55+0100
ISO_DATE=$(date --iso-8601=seconds)
FILE="/assets/screenshots/$ISO_DATE.jpg"

if ! test -f $FILE; then
    scrot --silent "/assets/screenshots/$ISO_DATE.jpg" --quality 95 --thumb 20
else
    echo "exists"
fi

exit 0
